export const Mithi = {
  body: "breasts",
  eyebrows: "serious",
  eyes: "simple",
  faceMask: false,
  facialHair: "none",
  hair: "long",
  hairColor: "black",
  lashes: false,
  lipColor: "purple",
  mask: false,
  mouth: "serious",
  skinTone: "brown",
  className: "avatar",
};

export const Diana = {
  body: "breasts",
  eyebrows: "leftLowered",
  eyes: "leftTwitch",
  faceMask: false,
  faceMaskColor: "black",
  facialHair: "none",
  hair: "afro",
  hairColor: "blue",
  lashes: true,
  lipColor: "green",
  mask: false,
  mouth: "lips",
  skinTone: "light",
  className: "avatar",
};

export const Mikong = {
  body: "chest",
  eyebrows: "angry",
  eyes: "content",
  faceMask: false,
  facialHair: "stubble",
  hair: "buzz",
  hairColor: "black",
  lashes: false,
  lipColor: "purple",
  mask: false,
  mouth: "openSmile",
  skinTone: "light",
  className: "avatar",
};
